'use client'
/*
  Auto-generated by Spline
*/
import React, { useRef } from 'react'
// import useSpline from '@splinetool/r3f-spline'
// import { OrthographicCamera } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/rNEsQ391gJBMRC7V/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#f5f6f7']} />
      <group {...props} dispose={null}>
        <scene name="Scene">
          {/* <mesh
            name="Path 2"
            geometry={nodes['Path 2'].geometry}
            material={materials['Path 2 Material']}
            position={[-240.3, 92.61, -10.68]}
            rotation={[-1.86, -1.07, -0.43]}
            scale={1}
          />
          <mesh
            name="Path 3"
            geometry={nodes['Path 3'].geometry}
            material={materials['Path 3 Material']}
            position={[-147.19, -233.4, -29.09]}
            rotation={[1.61, -0.42, -0.57]}
          />
          <mesh
            name="Path 4"
            geometry={nodes['Path 4'].geometry}
            material={materials['Path 4 Material']}
            position={[-148.47, 112.66, 132.02]}
            rotation={[-0.9, -0.44, 0.15]}
            scale={1}
          />
          <mesh
            name="Path"
            geometry={nodes.Path.geometry}
            material={materials['Path Material']}
            position={[-150.11, -38.61, 222.62]}
            rotation={[0.16, -0.39, 0.08]}
            scale={1}
          /> */}
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials['Sphere Material']}
            rotation={[Math.PI, -1.1, Math.PI]}
            scale={1}
          />
          {/* <directionalLight
            name="Directional Light"
            castShadow
            intensity={1}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1250}
            shadow-camera-right={1250}
            shadow-camera-top={1250}
            shadow-camera-bottom={-1250}
            position={[-811.97, 87.31, 300]}
          /> */}
          {/* <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} /> */}
          {/* <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" /> */}
        </scene>
      </group>
    </>
  )
}
