'use client'
/*
  Auto-generated by Spline
*/
import React, {useRef} from 'react'
import useSpline from '@splinetool/r3f-spline'
// import { OrthographicCamera } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function SceneTwo({ ...props }) {

  const { nodes, materials } = useSpline('https://prod.spline.design/rNEsQ391gJBMRC7V/scene.splinecode')

  return (
    <>
      <group {...props} dispose={null}>
      <mesh
        name="Rectangle"
        geometry={nodes.Rectangle.geometry}
        material={materials['Rectangle Material']}
      />
    </group>
    </>
  )
}